### ISSUE TITLE
Installation issue - debugger 1.1.1 on node-red 2.2.2  

### ISSUE THREAD

**Issue by rei-vilo** [node-red/node-red-debugger#10]
### Current Behavior

Once installed, **node-red-debugger** isn't listed among installed nodes.

### Expected Behavior

Once installed, **node-red-debugger** is listed among installed nodes.

### Steps To Reproduce

1. Call the menu **Manage** palette, **Install** then `node-red-debugger`
2. Click and confirm on **Install** 

After installation, node-red-debugger doesn't appears on the Nodes list.

3. Repeating the procedure throws a (normal) error `Module already loaded`

### Example flow

```
-----------------------------------------------------------
2022-03-14T14:07:15.936Z Install : node-red-debugger 1.1.1

2022-03-14T14:07:15.949Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-debugger@1.1.1
2022-03-14T14:07:17.069Z [out] 
2022-03-14T14:07:17.069Z [out] added 1 package in 915ms
2022-03-14T14:07:17.077Z rc=0

-----------------------------------------------------------
2022-03-14T14:07:20.111Z Install : node-red-debugger 1.1.1
```

### Environment

- node-red-debugger version: 1.1.1
- Node-RED version: 2.2.2
- Node.js version: 14.19.0
- npm version: 8.5.1
- Platform/OS: Debian 11.1
- Browser: Firefox 91.7.0esr (64 bits)

**Comment by knolleary** [comment]
The palette manager only lists modules that provide nodes to the palette. It does not list plugins. This is why the Debugger doesn't show up in that list.

This is not a bug with the debugger - the Palette Manager in the core of the editor needs updates to better handle plugins.

**Comment by rei-vilo** [comment]
Thank you for the clarification. 

Actually, I did search for documentation about the debugger but couldn't find much.
