### ISSUE TITLE
Feature: Allow to limit pause to certain tabs

### ISSUE THREAD

**Issue by Hypnos3** [node-red/node-red-debugger#6]
Please create a possibility that nodes which are paused can be limited.

I have a lot of Tabs and flows. Some of the flows (on certain tabs) process a lot of messages. Some of the messages must also be processed within a certain time. If the pause function stops all flows of node-red completely, I unfortunately cannot use the debugger. Here it would be helpful to be able to restrict the pause to certain tabs. The other tabs should continue to function as usual.

**Comment by knolleary** [comment]
In the next version (that will require the next Node-RED 2.0 beta) you will be able to tell it to only pause the node a breakpoint is on - all other nodes continue running. When you step the message forward, it will pause each node it arrives at.

The message list can also be filtered to only show messages on the current flow (tab).

I think this makes it more useful for 'busy' flows.
