### ISSUE TITLE
Node-red stops after UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by djivkov** [node-red/node-red-debugger#9]
### Current Behavior

Sometimes camera sends wrong data and the parser throws error:

Oct 31 23:04:23 raspberrypi Node-RED[12424]: (node:12424) UnhandledPromiseRejectionWarning: Error: Text data outside of root node.
Oct 31 23:04:23 raspberrypi Node-RED[12424]: Line: 6
Oct 31 23:04:23 raspberrypi Node-RED[12424]: Column: 12
Oct 31 23:04:23 raspberrypi Node-RED[12424]: Char: 1
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at error (/root/.node-red/node_modules/sax/lib/sax.js:651:10)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at strictFail (/root/.node-red/node_modules/sax/lib/sax.js:677:7)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at SAXParser.write (/root/.node-red/node_modules/sax/lib/sax.js:1035:15)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at Parser.exports.Parser.Parser.parseString (/root/.node-red/node_modules/xml2js/lib/parser.js:323:31)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at /root/.node-red/node_modules/xml2js/lib/parser.js:5:59
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at /root/.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes/Hikvision-config.js:179:41
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at Array.forEach (<anonymous>)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at handleChunk (/root/.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes/Hikvision-config.js:170:34)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at Readable.<anonymous> (/root/.node-red/node_modules/node-red-contrib-hikvision-ultimate/nodes/Hikvision-config.js:263:33)
Oct 31 23:04:23 raspberrypi Node-RED[12424]:     at Readable.emit (events.js:314:20)
Oct 31 23:04:23 raspberrypi Node-RED[12424]: (node:12424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi$
Oct 31 23:04:23 raspberrypi Node-RED[12424]: (node:12424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-ze$

### Steps To Reproduce

it's happening some times

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: 12.22.7
- npm version: 6.14.15
- Platform/OS: Raspbian
- Browser: Chrome
- Camera: DS-2CD2343G2-I, firmware: V5.7.1 build 211009

**Comment by knolleary** [comment]
What does this have to do with node-red-debugger?

**Comment by djivkov** [comment]
> What does this have to do with node-red-debugger?

Nothing

**Comment by knolleary** [comment]
This repository is for the `node-red-debugger` plugin for Node-RED. It isn't the place to report issues with nodes.

A quick look at the stacktrace shows the node causing this issue is `node-red-contrib-hikvision-ultimate` - so you should report the issue against that node's repository.

**Comment by djivkov** [comment]
My mistake. Sorry for taking your time.
